version: '3.8'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - "0.0.0.0:8890:9090"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local